/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'totalWorkouts' : bigint,
  'totalDistanceKm' : bigint,
  'totalCaloriesBurned' : bigint,
  'avgPace' : bigint,
}
export interface FitnessProfile {
  'age' : bigint,
  'primaryGoal' : string,
  'heightCm' : bigint,
  'fullName' : string,
  'weightKg' : bigint,
  'gender' : string,
}
export interface PublicTerritoryZone {
  'passCounts' : Array<[Principal, bigint]>,
  'currentOwner' : Principal,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export type Transform = ActorMethod<
  [TransformationInput],
  TransformationOutput
>;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutSession {
  'activityType' : string,
  'zone' : [] | [string],
  'distanceKm' : bigint,
  'durationSeconds' : bigint,
  'timestamp' : Time,
  'caloriesBurned' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getAllTerritoryZones' : ActorMethod<
    [],
    Array<[string, PublicTerritoryZone]>
  >,
  'getAnalyticsSummary' : ActorMethod<[Principal], AnalyticsSummary>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFitnessProfile' : ActorMethod<[], [] | [FitnessProfile]>,
  'getStripeConfigForRuntime' : ActorMethod<
    [[Principal, string]],
    [StripeConfiguration, [Principal, string]]
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalUserStats' : ActorMethod<
    [Principal],
    [] | [{ 'calories' : bigint, 'distance' : bigint }]
  >,
  'getUserOwnedZones' : ActorMethod<[Principal], bigint>,
  'getWorkoutSessions' : ActorMethod<[Principal], Array<WorkoutSession>>,
  'getZoneOwnership' : ActorMethod<[string], [] | [Principal]>,
  'getZonePassCounts' : ActorMethod<[string], Array<[Principal, bigint]>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listZones' : ActorMethod<[], Array<string>>,
  'recordWorkoutSession' : ActorMethod<[WorkoutSession], undefined>,
  'registerFitnessProfile' : ActorMethod<[FitnessProfile], undefined>,
  /**
   * / Admin-only function to initialize Stripe configuration (SaaS platform use only)
   */
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];