/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PublicTerritoryZone = IDL.Record({
  'passCounts' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
  'currentOwner' : IDL.Principal,
});
export const AnalyticsSummary = IDL.Record({
  'totalWorkouts' : IDL.Nat,
  'totalDistanceKm' : IDL.Nat,
  'totalCaloriesBurned' : IDL.Nat,
  'avgPace' : IDL.Nat,
});
export const FitnessProfile = IDL.Record({
  'age' : IDL.Nat,
  'primaryGoal' : IDL.Text,
  'heightCm' : IDL.Nat,
  'fullName' : IDL.Text,
  'weightKg' : IDL.Nat,
  'gender' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const Transform = IDL.Func(
    [TransformationInput],
    [TransformationOutput],
    ['query'],
  );
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Time = IDL.Int;
export const WorkoutSession = IDL.Record({
  'activityType' : IDL.Text,
  'zone' : IDL.Opt(IDL.Text),
  'distanceKm' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'timestamp' : Time,
  'caloriesBurned' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllTerritoryZones' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PublicTerritoryZone))],
      ['query'],
    ),
  'getAnalyticsSummary' : IDL.Func(
      [IDL.Principal],
      [AnalyticsSummary],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFitnessProfile' : IDL.Func([], [IDL.Opt(FitnessProfile)], ['query']),
  'getStripeConfigForRuntime' : IDL.Func(
      [Transform],
      [StripeConfiguration, Transform],
      [],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalUserStats' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Record({ 'calories' : IDL.Nat, 'distance' : IDL.Nat }))],
      ['query'],
    ),
  'getUserOwnedZones' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getWorkoutSessions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WorkoutSession)],
      ['query'],
    ),
  'getZoneOwnership' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getZonePassCounts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listZones' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'recordWorkoutSession' : IDL.Func([WorkoutSession], [], []),
  'registerFitnessProfile' : IDL.Func([FitnessProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PublicTerritoryZone = IDL.Record({
    'passCounts' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
    'currentOwner' : IDL.Principal,
  });
  const AnalyticsSummary = IDL.Record({
    'totalWorkouts' : IDL.Nat,
    'totalDistanceKm' : IDL.Nat,
    'totalCaloriesBurned' : IDL.Nat,
    'avgPace' : IDL.Nat,
  });
  const FitnessProfile = IDL.Record({
    'age' : IDL.Nat,
    'primaryGoal' : IDL.Text,
    'heightCm' : IDL.Nat,
    'fullName' : IDL.Text,
    'weightKg' : IDL.Nat,
    'gender' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const Transform = IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    );
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Time = IDL.Int;
  const WorkoutSession = IDL.Record({
    'activityType' : IDL.Text,
    'zone' : IDL.Opt(IDL.Text),
    'distanceKm' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'timestamp' : Time,
    'caloriesBurned' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllTerritoryZones' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PublicTerritoryZone))],
        ['query'],
      ),
    'getAnalyticsSummary' : IDL.Func(
        [IDL.Principal],
        [AnalyticsSummary],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFitnessProfile' : IDL.Func([], [IDL.Opt(FitnessProfile)], ['query']),
    'getStripeConfigForRuntime' : IDL.Func(
        [Transform],
        [StripeConfiguration, Transform],
        [],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalUserStats' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Record({ 'calories' : IDL.Nat, 'distance' : IDL.Nat }))],
        ['query'],
      ),
    'getUserOwnedZones' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getWorkoutSessions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'getZoneOwnership' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getZonePassCounts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listZones' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'recordWorkoutSession' : IDL.Func([WorkoutSession], [], []),
    'registerFitnessProfile' : IDL.Func([FitnessProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };